export const CHANGE_TAB = "CHANGE_TAB";
export const MOBILE_DRAWER = "MOBILE_DRAWER";
export const CHANGE_PAGE_ANIMATION = "CHANGE_PAGE_ANIMATION";
export const CHANGE_AUTH_PAGE = "CHANGE_AUTH_PAGE";
